name: CiCd
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
            go-version: '1.18.0'
      - name: Install dependencies
        run: |
          go version
          go mod tidy
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: go build .
      - name: Run vet & lint
        run: |
          go vet .
          golint .
      - name: Run testing
        run: cd && go -v # 'test' replace with name of the directory, where our tests will be placed
